// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TID-G-006', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('TID-G-006', async function() {
    await driver.get("https://banihiddenparadiseresort.onrender.com/")
    await driver.manage().window().setRect({ width: 1470, height: 832 })
    await driver.findElement(By.linkText("Reservations")).click()
    await driver.findElement(By.css(".flex:nth-child(1) > .p-1")).click()
    await driver.findElement(By.css(".flex:nth-child(1) > .p-1")).sendKeys("2024-11-26")
    await driver.findElement(By.css(".flex:nth-child(2) > .p-1")).click()
    await driver.findElement(By.css(".flex:nth-child(2) > .p-1")).sendKeys("2024-11-28")
    await driver.findElement(By.css(".flex:nth-child(1) > .p-1")).click()
    await driver.findElement(By.css(".flex:nth-child(1) > .p-1")).sendKeys("2024-12-17")
    await driver.findElement(By.css(".flex:nth-child(2) > .p-1")).click()
    await driver.findElement(By.css(".flex:nth-child(2) > .p-1")).sendKeys("2024-12-20")
    await driver.findElement(By.css(".p-2")).click()
    await driver.findElement(By.css(".flex:nth-child(2) > .ml-5")).click()
    await driver.findElement(By.xpath("//div[@id=\'root\']/div[3]/div/div[3]/div/div[2]/div/div/div[3]/div/form/div[7]/div/div/input")).click()
    await driver.findElement(By.xpath("//div[@id=\'root\']/div[3]/div/div[3]/div/div[2]/div/div/div[3]/div/form/div[7]/div/div/input")).sendKeys("John")
    await driver.findElement(By.xpath("//div[@id=\'root\']/div[3]/div/div[3]/div/div[2]/div/div/div[3]/div/form/div[8]/div/div/input")).click()
    await driver.findElement(By.xpath("//div[@id=\'root\']/div[3]/div/div[3]/div/div[2]/div/div/div[3]/div/form/div[8]/div/div/input")).sendKeys("Doe")
    await driver.findElement(By.xpath("//div[@id=\'root\']/div[3]/div/div[3]/div/div[2]/div/div/div[3]/div/form/div[9]/div/div/input")).click()
    await driver.findElement(By.xpath("//div[@id=\'root\']/div[3]/div/div[3]/div/div[2]/div/div/div[3]/div/form/div[9]/div/div/input")).sendKeys("johndoe@example.com")
    await driver.findElement(By.xpath("//div[@id=\'root\']/div[3]/div/div[3]/div/div[2]/div/div/div[3]/div/form/div[10]/div/div/input")).click()
    await driver.findElement(By.xpath("//div[@id=\'root\']/div[3]/div/div[3]/div/div[2]/div/div/div[3]/div/form/div[10]/div/div/input")).sendKeys("091745362”")
    await driver.findElement(By.xpath("//div[@id=\'root\']/div[3]/div/div[3]/div/div[2]/div/div/div[3]/div/form/div[11]/div/div/input")).click()
    await driver.findElement(By.xpath("//div[@id=\'root\']/div[3]/div/div[3]/div/div[2]/div/div/div[3]/div/form/div[10]/div/div/input")).click()
    await driver.findElement(By.xpath("//div[@id=\'root\']/div[3]/div/div[3]/div/div[2]/div/div/div[3]/div/form/div[10]/div/div/input")).sendKeys("091745362")
    await driver.findElement(By.xpath("//div[@id=\'root\']/div[3]/div/div[3]/div/div[2]/div/div/div[3]/div/form/div[11]/div/div/input")).click()
    await driver.findElement(By.xpath("//div[@id=\'root\']/div[3]/div/div[3]/div/div[2]/div/div/div[3]/div/form/div[11]/div/div/input")).sendKeys("Manila")
    await driver.findElement(By.css(".bg-\\[\\#CBA989\\]")).click()
    {
      const element = await driver.findElement(By.css(".bg-\\[\\#CBA989\\]"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".top-2")).click()
  })
})
