// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TID-G-001', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('TID-G-001', async function() {
    await driver.get("https://banihiddenparadiseresort.onrender.com/")
    await driver.manage().window().setRect({ width: 1470, height: 832 })
    await driver.findElement(By.linkText("Reservations")).click()
    await driver.findElement(By.css(".flex:nth-child(1) > .p-1")).click()
    await driver.findElement(By.css(".flex:nth-child(1) > .p-1")).sendKeys("2024-11-06")
    await driver.findElement(By.css(".flex:nth-child(2) > .p-1")).click()
    await driver.findElement(By.css(".flex:nth-child(2) > .p-1")).sendKeys("2024-11-26")
    await driver.findElement(By.css(".p-2")).click()
  })
})
