// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TID-G-010- Multiple Reservation Submission Without Page Refresh and Database Verification', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('TID-G-010- Multiple Reservation Submission Without Page Refresh and Database Verification', async function() {
    await driver.get("https://banihiddenparadiseresort.onrender.com/")
    await driver.manage().window().setRect({ width: 1265, height: 1372 })
    await driver.findElement(By.linkText("Reservations")).click()
    await driver.findElement(By.css(".flex:nth-child(1) > .p-1")).click()
    await driver.findElement(By.css(".flex:nth-child(1) > .p-1")).sendKeys("2025-01-01")
    await driver.findElement(By.css(".flex:nth-child(2) > .p-1")).click()
    await driver.findElement(By.css(".flex:nth-child(2) > .p-1")).sendKeys("2025-01-03")
    await driver.findElement(By.id("mantine-mpz2nae7r")).click()
    {
      const dropdown = await driver.findElement(By.id("mantine-8lhc31nif"))
      await dropdown.findElement(By.xpath("//option[. = '4']")).click()
    }
    await driver.findElement(By.id("mantine-cloy2z5rs")).click()
    {
      const dropdown = await driver.findElement(By.id("mantine-y7n20d067"))
      await dropdown.findElement(By.xpath("//option[. = '1']")).click()
    }
    await driver.findElement(By.css(".p-2")).click()
    await driver.findElement(By.css(".flex:nth-child(2) > .ml-5")).click()
    await driver.findElement(By.id("mantine-bsygb0q44")).click()
    {
      const dropdown = await driver.findElement(By.id("mantine-fqo8kpgkq"))
      await dropdown.findElement(By.xpath("//option[. = 'Yes']")).click()
    }
    await driver.findElement(By.id("mantine-2mgjw6iwm")).click()
    await driver.findElement(By.xpath("//div[7]/div/div/input")).sendKeys("Barbara")
    await driver.findElement(By.xpath("//div[8]/div/div/input")).sendKeys("Palvin")
    await driver.findElement(By.xpath("//div[9]/div/div/input")).sendKeys("barbarapalvin@gmail.com")
    await driver.findElement(By.xpath("//div[10]/div/div/input")).sendKeys("09759927564")
    await driver.findElement(By.xpath("//div[11]/div/div/input")).sendKeys("Manila")
    await driver.findElement(By.css(".bg-\\[\\#CBA989\\]")).click()
    await driver.findElement(By.css(".top-2")).click()
    await driver.findElement(By.css(".flex:nth-child(1) > .p-1")).click()
    await driver.findElement(By.css(".flex:nth-child(1) > .p-1")).sendKeys("2025-01-05")
    await driver.findElement(By.css(".flex:nth-child(2) > .p-1")).click()
    await driver.findElement(By.css(".flex:nth-child(2) > .p-1")).sendKeys("2025-01-07")
    await driver.findElement(By.id("mantine-mpz2nae7r")).click()
    {
      const dropdown = await driver.findElement(By.id("mantine-ox5p09yqb"))
      await dropdown.findElement(By.xpath("//option[. = '2']")).click()
    }
    await driver.findElement(By.id("mantine-cloy2z5rs")).click()
    {
      const dropdown = await driver.findElement(By.id("mantine-ox5p09yqb"))
      await dropdown.findElement(By.xpath("//option[. = '0']")).click()
    }
    await driver.findElement(By.css(".p-2")).click()
    await driver.findElement(By.css(".flex:nth-child(5) > .ml-5")).click()
    await driver.findElement(By.id("mantine-ub4fche3y")).click()
    await driver.findElement(By.xpath("//div[7]/div/div/input")).sendKeys("Christopher")
    await driver.findElement(By.xpath("//div[8]/div/div/input")).sendKeys("Briney")
    await driver.findElement(By.xpath("//div[9]/div/div/input")).sendKeys("christopherbriney@gmail.com")
    await driver.findElement(By.xpath("//div[10]/div/div/input")).sendKeys("09881659264")
    await driver.findElement(By.xpath("//div[11]/div/div/input")).sendKeys("Makati City")
    await driver.findElement(By.css(".col-span-2 > .p-1")).sendKeys("extra pillow")
    await driver.findElement(By.css(".bg-\\[\\#CBA989\\]")).click()
    await driver.findElement(By.css(".top-2")).click()
  })
})
