// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TID-G-012- Room Availability Check and Error Message for Double Booking', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('TID-G-012- Room Availability Check and Error Message for Double Booking', async function() {
    await driver.get("https://banihiddenparadiseresort.onrender.com/")
    await driver.manage().window().setRect({ width: 1265, height: 1372 })
    await driver.findElement(By.linkText("Reservations")).click()
    await driver.findElement(By.css(".flex:nth-child(1) > .p-1")).click()
    await driver.findElement(By.css(".flex:nth-child(1) > .p-1")).sendKeys("2024-12-10")
    await driver.findElement(By.css(".flex:nth-child(2) > .p-1")).click()
    await driver.findElement(By.css(".flex:nth-child(2) > .p-1")).sendKeys("2024-12-12")
    await driver.findElement(By.id("mantine-9mj2x8qh0")).click()
    {
      const dropdown = await driver.findElement(By.id("mantine-qcs781urb"))
      await dropdown.findElement(By.xpath("//option[. = '6']")).click()
    }
    await driver.findElement(By.css(".p-2")).click()
    await driver.findElement(By.css(".flex:nth-child(2) > .ml-5")).click()
    await driver.findElement(By.id("mantine-lhxc0llot")).click()
    {
      const dropdown = await driver.findElement(By.id("mantine-631dqxtza"))
      await dropdown.findElement(By.xpath("//option[. = 'Yes']")).click()
    }
    await driver.findElement(By.id("mantine-w01leb6c5")).click()
    await driver.findElement(By.xpath("//div[7]/div/div/input")).sendKeys("Jeremiah")
    await driver.findElement(By.xpath("//div[8]/div/div/input")).sendKeys("Fisher")
    await driver.findElement(By.xpath("//div[9]/div/div/input")).sendKeys("jeremiahfisher@gmail.com")
    await driver.findElement(By.xpath("//div[10]/div/div/input")).sendKeys("09721175864")
    await driver.findElement(By.xpath("//div[11]/div/div/input")).sendKeys("Taguig")
    await driver.findElement(By.css(".col-span-2 > .p-1")).sendKeys("extra pillow")
    await driver.findElement(By.css(".bg-\\[\\#CBA989\\]")).click()
    await driver.findElement(By.css(".top-2")).click()
    await driver.findElement(By.css(".flex:nth-child(1) > .p-1")).click()
    await driver.findElement(By.css(".flex:nth-child(1) > .p-1")).sendKeys("2024-12-10")
    await driver.findElement(By.css(".flex:nth-child(2) > .p-1")).click()
    await driver.findElement(By.css(".flex:nth-child(2) > .p-1")).sendKeys("2024-12-12")
    await driver.findElement(By.id("mantine-fkbvh05n4")).click()
    {
      const dropdown = await driver.findElement(By.id("mantine-55yf6bjir"))
      await dropdown.findElement(By.xpath("//option[. = '5']")).click()
    }
    await driver.findElement(By.id("mantine-ryd8sdc3k")).click()
    await driver.findElement(By.css(".p-2")).click()
  })
})
