// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TID-G-009- Reservation Submission and Database Verification for Room Booking', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('TID-G-009- Reservation Submission and Database Verification for Room Booking', async function() {
    await driver.get("https://banihiddenparadiseresort.onrender.com/")
    await driver.manage().window().setRect({ width: 1294, height: 1399 })
    await driver.findElement(By.linkText("Reservations")).click()
    {
      const element = await driver.findElement(By.linkText("Restaurants"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".flex:nth-child(1) > .p-1")).click()
    await driver.findElement(By.css(".flex:nth-child(1) > .p-1")).click()
    await driver.findElement(By.css(".flex:nth-child(1) > .p-1")).sendKeys("2024-12-20")
    await driver.findElement(By.css(".flex:nth-child(2) > .p-1")).click()
    await driver.findElement(By.css(".flex:nth-child(2) > .p-1")).sendKeys("2024-12-22")
    await driver.findElement(By.id("mantine-jpirmnwfk")).click()
    {
      const dropdown = await driver.findElement(By.id("mantine-mpsd80fuw"))
      await dropdown.findElement(By.xpath("//option[. = '2']")).click()
    }
    await driver.findElement(By.id("mantine-7z4cet4qm")).click()
    {
      const dropdown = await driver.findElement(By.id("mantine-hnw02ndda"))
      await dropdown.findElement(By.xpath("//option[. = '1']")).click()
    }
    await driver.findElement(By.css(".p-2")).click()
    await driver.findElement(By.css(".flex:nth-child(5) > .ml-5")).click()
    await driver.findElement(By.css("#mantine-yl5bx3jmk")).click()
    {
      const dropdown = await driver.findElement(By.id("mantine-ky2sj2set"))
      await dropdown.findElement(By.xpath("//option[. = 'No']")).click()
    }
    await driver.findElement(By.id("mantine-pvazm04bt")).click()
    await driver.findElement(By.xpath("//div[7]/div/div/input")).sendKeys("Taylor")
    await driver.findElement(By.id("mantine-gnd2jov5k")).click()
    await driver.findElement(By.xpath("//div[8]/div/div/input")).sendKeys("Hill")
    await driver.findElement(By.id("mantine-8jt04jkjf")).click()
    await driver.findElement(By.xpath("//div[9]/div/div/input")).sendKeys("taylorhill@gmail.com")
    await driver.findElement(By.id("mantine-0bihvxlcv")).click()
    await driver.findElement(By.xpath("//div[10]/div/div/input")).sendKeys("09829465728")
    await driver.findElement(By.id("mantine-px75dz6rp")).click()
    await driver.findElement(By.xpath("//div[11]/div/div/input")).sendKeys("Marikina City")
    await driver.findElement(By.css(".col-span-2 > .p-1")).click()
    await driver.findElement(By.css(".col-span-2 > .p-1")).sendKeys("Late check-in")
    await driver.findElement(By.css(".bg-\\[\\#CBA989\\]")).click()
    await driver.findElement(By.css(".top-2")).click()
    await driver.close()
  })
})
