// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TID-G-011- Reservation Submission and Success Message Display Verification', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('TID-G-011- Reservation Submission and Success Message Display Verification', async function() {
    await driver.get("https://banihiddenparadiseresort.onrender.com/")
    await driver.manage().window().setRect({ width: 1265, height: 1372 })
    await driver.findElement(By.linkText("Reservations")).click()
    await driver.findElement(By.css(".flex:nth-child(1) > .p-1")).click()
    await driver.findElement(By.css(".flex:nth-child(1) > .p-1")).sendKeys("2025-02-14")
    await driver.findElement(By.css(".flex:nth-child(2) > .p-1")).click()
    await driver.findElement(By.css(".flex:nth-child(2) > .p-1")).sendKeys("2025-02-16")
    await driver.findElement(By.id("mantine-acl18tnms")).click()
    {
      const dropdown = await driver.findElement(By.id("mantine-xnte8y61z"))
      await dropdown.findElement(By.xpath("//option[. = '2']")).click()
    }
    await driver.findElement(By.css(".p-2")).click()
    await driver.findElement(By.css(".flex:nth-child(7) > .ml-5")).click()
    await driver.findElement(By.id("mantine-c5j9jrb0f")).click()
    await driver.findElement(By.xpath("//div[7]/div/div/input")).sendKeys("Adriana")
    await driver.findElement(By.xpath("//div[8]/div/div/input")).sendKeys("Lima")
    await driver.findElement(By.xpath("//div[9]/div/div/input")).sendKeys("adrianalima@gmail.com")
    await driver.findElement(By.xpath("//div[10]/div/div/input")).sendKeys("098473657284")
    await driver.findElement(By.xpath("//div[11]/div/div/input")).sendKeys("Alabang")
    await driver.findElement(By.css(".col-span-2 > .p-1")).sendKeys("1 bottle of red wine")
    await driver.findElement(By.css(".bg-\\[\\#CBA989\\]")).click()
    await driver.findElement(By.id("mantine-htqtn42ft")).click()
    await driver.findElement(By.xpath("//div[10]/div/div/input")).sendKeys("09847365728")
    await driver.findElement(By.css(".bg-\\[\\#CBA989\\]")).click()
    await driver.findElement(By.css(".mt-4:nth-child(3)")).click()
    await driver.findElement(By.css(".mt-4:nth-child(3)")).click()
    await driver.findElement(By.css(".top-2")).click()
  })
})
